### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [shop-instore/GTM-Pixel_Inventory_Collector#1]
https://github.com/shop-instore/GTM-Pixel_Inventory_Collector/blob/7ab0ce97f10ee33545c0489b1f6a7b46a260377b/template.tpl#L86

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by shop-instore** [comment]
Updated .tpl to use EncodeUriComponent(). Thanks for reviewing!

**Comment by semisight** [comment]
Hello!

Would you mind updating metadata.yaml to point to the newest/fixed commit? Then we can merge your template.
